apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-filemanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filemanager
  template:
    metadata:
      labels:
        app: filemanager
    spec:
      containers:
      - name: kubernetes-filemanager
        image: juanpmc/practica2server:1.0
